[versions]
jdk = "25"

minecraft = "26.2"
fabric-loom = "1.17-SNAPSHOT"
fabric-loader = "0.19.3"
fabric-api = "0.153.0+26.2"

kotlin = "2.4.0"
fabric-kotlin = "1.13.12+kotlin.2.4.0"

liquidbounce = "0.40.1+26.2-SNAPSHOT"

polyglot = "25.0.3"
okhttp = "5.5.0"
fastutil4k = "0.2.8"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
liquidbounce = { group = "net.ccbluex", name = "liquidbounce", version.ref = "liquidbounce" }

polyglot = { group = "org.graalvm.polyglot", name = "polyglot", version.ref = "polyglot" }
polyglot-tools = { group = "org.graalvm.polyglot", name = "tools-community", version.ref = "polyglot" }
polyglot-js = { group = "org.graalvm.polyglot", name = "js-community", version.ref = "polyglot" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
fastutil4k-extensionsOnly = { group = "net.ccbluex", name = "fastutil4k-extensions-only", version.ref = "fastutil4k" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
